//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YANFOE {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YANFOE.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Banner.
        /// </summary>
        internal static string DisplayPictureUserControl_UpdateLayout_Alternative_Banner {
            get {
                return ResourceManager.GetString("DisplayPictureUserControl_UpdateLayout_Alternative_Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Fanart.
        /// </summary>
        internal static string DisplayPictureUserControl_UpdateLayout_Alternative_Fanart {
            get {
                return ResourceManager.GetString("DisplayPictureUserControl_UpdateLayout_Alternative_Fanart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Posters.
        /// </summary>
        internal static string DisplayPictureUserControl_UpdateLayout_Alternative_Posters {
            get {
                return ResourceManager.GetString("DisplayPictureUserControl_UpdateLayout_Alternative_Posters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Screenshots.
        /// </summary>
        internal static string DisplayPictureUserControl_UpdateLayout_Alternative_Screenshots {
            get {
                return ResourceManager.GetString("DisplayPictureUserControl_UpdateLayout_Alternative_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string FrmMain_Menu_About {
            get {
                return ResourceManager.GetString("FrmMain_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string FrmMain_Menu_Edit {
            get {
                return ResourceManager.GetString("FrmMain_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FrmMain_Menu_File {
            get {
                return ResourceManager.GetString("FrmMain_Menu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string FrmMain_Menu_File_Exit {
            get {
                return ResourceManager.GetString("FrmMain_Menu_File_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string FrmMain_Menu_Tools {
            get {
                return ResourceManager.GetString("FrmMain_Menu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Scraper Group Manager.
        /// </summary>
        internal static string FrmMain_Menu_Tools_MovieScraperGroupManager {
            get {
                return ResourceManager.GetString("FrmMain_Menu_Tools_MovieScraperGroupManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jpeg (*.jpg)|*.jpg|All files (*.*)|*.*.
        /// </summary>
        internal static string SetManagerUserControl_PickFileDialog_Jpeg____jpg____jpg_All_files__________ {
            get {
                return ResourceManager.GetString("SetManagerUserControl_PickFileDialog_Jpeg____jpg____jpg_All_files__________", resourceCulture);
            }
        }
    }
}
